// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edda.core.proto

package eddaX

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Host struct {
	Machineid            string   `protobuf:"bytes,1,opt,name=machineid,proto3" json:"machineid,omitempty"`
	Hypervisor           string   `protobuf:"bytes,2,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	Architecture         string   `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetMachineid() string {
	if m != nil {
		return m.Machineid
	}
	return ""
}

func (m *Host) GetHypervisor() string {
	if m != nil {
		return m.Hypervisor
	}
	return ""
}

func (m *Host) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

type Product struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor               string   `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Serial               string   `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Product) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

// 主板
type Board struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor               string   `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Serial               string   `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Board) Reset()         { *m = Board{} }
func (m *Board) String() string { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()    {}
func (*Board) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{2}
}

func (m *Board) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Board.Unmarshal(m, b)
}
func (m *Board) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Board.Marshal(b, m, deterministic)
}
func (m *Board) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Board.Merge(m, src)
}
func (m *Board) XXX_Size() int {
	return xxx_messageInfo_Board.Size(m)
}
func (m *Board) XXX_DiscardUnknown() {
	xxx_messageInfo_Board.DiscardUnknown(m)
}

var xxx_messageInfo_Board proto.InternalMessageInfo

func (m *Board) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Board) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Board) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type Bios struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bios) Reset()         { *m = Bios{} }
func (m *Bios) String() string { return proto.CompactTextString(m) }
func (*Bios) ProtoMessage()    {}
func (*Bios) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{3}
}

func (m *Bios) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bios.Unmarshal(m, b)
}
func (m *Bios) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bios.Marshal(b, m, deterministic)
}
func (m *Bios) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bios.Merge(m, src)
}
func (m *Bios) XXX_Size() int {
	return xxx_messageInfo_Bios.Size(m)
}
func (m *Bios) XXX_DiscardUnknown() {
	xxx_messageInfo_Bios.DiscardUnknown(m)
}

var xxx_messageInfo_Bios proto.InternalMessageInfo

func (m *Bios) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

type Cpu struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Speed                uint32   `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Cache                uint32   `protobuf:"varint,4,opt,name=cache,proto3" json:"cache,omitempty"`
	Cpus                 uint32   `protobuf:"varint,5,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Cores                uint32   `protobuf:"varint,6,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads              uint32   `protobuf:"varint,7,opt,name=threads,proto3" json:"threads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cpu) Reset()         { *m = Cpu{} }
func (m *Cpu) String() string { return proto.CompactTextString(m) }
func (*Cpu) ProtoMessage()    {}
func (*Cpu) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{4}
}

func (m *Cpu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cpu.Unmarshal(m, b)
}
func (m *Cpu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cpu.Marshal(b, m, deterministic)
}
func (m *Cpu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cpu.Merge(m, src)
}
func (m *Cpu) XXX_Size() int {
	return xxx_messageInfo_Cpu.Size(m)
}
func (m *Cpu) XXX_DiscardUnknown() {
	xxx_messageInfo_Cpu.DiscardUnknown(m)
}

var xxx_messageInfo_Cpu proto.InternalMessageInfo

func (m *Cpu) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Cpu) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Cpu) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Cpu) GetCache() uint32 {
	if m != nil {
		return m.Cache
	}
	return 0
}

func (m *Cpu) GetCpus() uint32 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Cpu) GetCores() uint32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *Cpu) GetThreads() uint32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

type Mem struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Speed                uint32   `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mem) Reset()         { *m = Mem{} }
func (m *Mem) String() string { return proto.CompactTextString(m) }
func (*Mem) ProtoMessage()    {}
func (*Mem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{5}
}

func (m *Mem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mem.Unmarshal(m, b)
}
func (m *Mem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mem.Marshal(b, m, deterministic)
}
func (m *Mem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mem.Merge(m, src)
}
func (m *Mem) XXX_Size() int {
	return xxx_messageInfo_Mem.Size(m)
}
func (m *Mem) XXX_DiscardUnknown() {
	xxx_messageInfo_Mem.DiscardUnknown(m)
}

var xxx_messageInfo_Mem proto.InternalMessageInfo

func (m *Mem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Mem) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Network struct {
	Driver               string   `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Macaddress           string   `protobuf:"bytes,2,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Speed                uint32   `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{6}
}

func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Network) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *Network) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Hardware struct {
	Host                 *Host      `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Product              *Product   `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Board                *Board     `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Bios                 *Bios      `protobuf:"bytes,4,opt,name=bios,proto3" json:"bios,omitempty"`
	Cpu                  *Cpu       `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem                  *Mem       `protobuf:"bytes,6,opt,name=mem,proto3" json:"mem,omitempty"`
	Networks             []*Network `protobuf:"bytes,7,rep,name=networks,proto3" json:"networks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Hardware) Reset()         { *m = Hardware{} }
func (m *Hardware) String() string { return proto.CompactTextString(m) }
func (*Hardware) ProtoMessage()    {}
func (*Hardware) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{7}
}

func (m *Hardware) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware.Unmarshal(m, b)
}
func (m *Hardware) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware.Marshal(b, m, deterministic)
}
func (m *Hardware) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware.Merge(m, src)
}
func (m *Hardware) XXX_Size() int {
	return xxx_messageInfo_Hardware.Size(m)
}
func (m *Hardware) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware proto.InternalMessageInfo

func (m *Hardware) GetHost() *Host {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Hardware) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Hardware) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Hardware) GetBios() *Bios {
	if m != nil {
		return m.Bios
	}
	return nil
}

func (m *Hardware) GetCpu() *Cpu {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *Hardware) GetMem() *Mem {
	if m != nil {
		return m.Mem
	}
	return nil
}

func (m *Hardware) GetNetworks() []*Network {
	if m != nil {
		return m.Networks
	}
	return nil
}

type Attrs struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Start                int64    `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	Hwmd5                string   `protobuf:"bytes,4,opt,name=hwmd5,proto3" json:"hwmd5,omitempty"`
	Now                  int64    `protobuf:"varint,5,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attrs) Reset()         { *m = Attrs{} }
func (m *Attrs) String() string { return proto.CompactTextString(m) }
func (*Attrs) ProtoMessage()    {}
func (*Attrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{8}
}

func (m *Attrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attrs.Unmarshal(m, b)
}
func (m *Attrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attrs.Marshal(b, m, deterministic)
}
func (m *Attrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attrs.Merge(m, src)
}
func (m *Attrs) XXX_Size() int {
	return xxx_messageInfo_Attrs.Size(m)
}
func (m *Attrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Attrs.DiscardUnknown(m)
}

var xxx_messageInfo_Attrs proto.InternalMessageInfo

func (m *Attrs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attrs) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Attrs) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Attrs) GetHwmd5() string {
	if m != nil {
		return m.Hwmd5
	}
	return ""
}

func (m *Attrs) GetNow() int64 {
	if m != nil {
		return m.Now
	}
	return 0
}

type Node struct {
	Attrs                *Attrs    `protobuf:"bytes,1,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Hardware             *Hardware `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{9}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAttrs() *Attrs {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Node) GetHardware() *Hardware {
	if m != nil {
		return m.Hardware
	}
	return nil
}

type SerialNum struct {
	Sid                  string           `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Nodes                map[string]*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Date                 int64            `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SerialNum) Reset()         { *m = SerialNum{} }
func (m *SerialNum) String() string { return proto.CompactTextString(m) }
func (*SerialNum) ProtoMessage()    {}
func (*SerialNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{10}
}

func (m *SerialNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerialNum.Unmarshal(m, b)
}
func (m *SerialNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerialNum.Marshal(b, m, deterministic)
}
func (m *SerialNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerialNum.Merge(m, src)
}
func (m *SerialNum) XXX_Size() int {
	return xxx_messageInfo_SerialNum.Size(m)
}
func (m *SerialNum) XXX_DiscardUnknown() {
	xxx_messageInfo_SerialNum.DiscardUnknown(m)
}

var xxx_messageInfo_SerialNum proto.InternalMessageInfo

func (m *SerialNum) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SerialNum) GetNodes() map[string]*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *SerialNum) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type App struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Attrs                []*Attr  `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty"`
	Expire               int64    `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	Instance             int64    `protobuf:"varint,5,opt,name=instance,proto3" json:"instance,omitempty"`
	MaxLifeCycle         int64    `protobuf:"varint,6,opt,name=maxLifeCycle,proto3" json:"maxLifeCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{11}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *App) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *App) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *App) GetInstance() int64 {
	if m != nil {
		return m.Instance
	}
	return 0
}

func (m *App) GetMaxLifeCycle() int64 {
	if m != nil {
		return m.MaxLifeCycle
	}
	return 0
}

type Attr struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attr) Reset()         { *m = Attr{} }
func (m *Attr) String() string { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()    {}
func (*Attr) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{12}
}

func (m *Attr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attr.Unmarshal(m, b)
}
func (m *Attr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attr.Marshal(b, m, deterministic)
}
func (m *Attr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attr.Merge(m, src)
}
func (m *Attr) XXX_Size() int {
	return xxx_messageInfo_Attr.Size(m)
}
func (m *Attr) XXX_DiscardUnknown() {
	xxx_messageInfo_Attr.DiscardUnknown(m)
}

var xxx_messageInfo_Attr proto.InternalMessageInfo

func (m *Attr) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attr) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attr) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type License struct {
	Lid                  string            `protobuf:"bytes,1,opt,name=lid,proto3" json:"lid,omitempty"`
	Sid                  string            `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Devices              map[string]string `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Generate             int64             `protobuf:"varint,4,opt,name=generate,proto3" json:"generate,omitempty"`
	Update               int64             `protobuf:"varint,5,opt,name=update,proto3" json:"update,omitempty"`
	LifeCycle            int64             `protobuf:"varint,6,opt,name=lifeCycle,proto3" json:"lifeCycle,omitempty"`
	Apps                 map[string]*App   `protobuf:"bytes,7,rep,name=apps,proto3" json:"apps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *License) Reset()         { *m = License{} }
func (m *License) String() string { return proto.CompactTextString(m) }
func (*License) ProtoMessage()    {}
func (*License) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{13}
}

func (m *License) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_License.Unmarshal(m, b)
}
func (m *License) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_License.Marshal(b, m, deterministic)
}
func (m *License) XXX_Merge(src proto.Message) {
	xxx_messageInfo_License.Merge(m, src)
}
func (m *License) XXX_Size() int {
	return xxx_messageInfo_License.Size(m)
}
func (m *License) XXX_DiscardUnknown() {
	xxx_messageInfo_License.DiscardUnknown(m)
}

var xxx_messageInfo_License proto.InternalMessageInfo

func (m *License) GetLid() string {
	if m != nil {
		return m.Lid
	}
	return ""
}

func (m *License) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *License) GetDevices() map[string]string {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *License) GetGenerate() int64 {
	if m != nil {
		return m.Generate
	}
	return 0
}

func (m *License) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

func (m *License) GetLifeCycle() int64 {
	if m != nil {
		return m.LifeCycle
	}
	return 0
}

func (m *License) GetApps() map[string]*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AuthReq struct {
	Cipher               *Cipher         `protobuf:"bytes,1,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Apps                 map[string]*App `protobuf:"bytes,3,rep,name=apps,proto3" json:"apps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{14}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetCipher() *Cipher {
	if m != nil {
		return m.Cipher
	}
	return nil
}

func (m *AuthReq) GetApps() map[string]*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AuthResp struct {
	Cipher               *Cipher  `protobuf:"bytes,1,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Lic                  *License `protobuf:"bytes,2,opt,name=lic,proto3" json:"lic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{15}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetCipher() *Cipher {
	if m != nil {
		return m.Cipher
	}
	return nil
}

func (m *AuthResp) GetLic() *License {
	if m != nil {
		return m.Lic
	}
	return nil
}

type UntiedReq struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UntiedReq) Reset()         { *m = UntiedReq{} }
func (m *UntiedReq) String() string { return proto.CompactTextString(m) }
func (*UntiedReq) ProtoMessage()    {}
func (*UntiedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{16}
}

func (m *UntiedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UntiedReq.Unmarshal(m, b)
}
func (m *UntiedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UntiedReq.Marshal(b, m, deterministic)
}
func (m *UntiedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UntiedReq.Merge(m, src)
}
func (m *UntiedReq) XXX_Size() int {
	return xxx_messageInfo_UntiedReq.Size(m)
}
func (m *UntiedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UntiedReq.DiscardUnknown(m)
}

var xxx_messageInfo_UntiedReq proto.InternalMessageInfo

func (m *UntiedReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *UntiedReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Clear struct {
	Lic                  *License `protobuf:"bytes,1,opt,name=lic,proto3" json:"lic,omitempty"`
	Cipher               *Cipher  `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clear) Reset()         { *m = Clear{} }
func (m *Clear) String() string { return proto.CompactTextString(m) }
func (*Clear) ProtoMessage()    {}
func (*Clear) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{17}
}

func (m *Clear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clear.Unmarshal(m, b)
}
func (m *Clear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clear.Marshal(b, m, deterministic)
}
func (m *Clear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clear.Merge(m, src)
}
func (m *Clear) XXX_Size() int {
	return xxx_messageInfo_Clear.Size(m)
}
func (m *Clear) XXX_DiscardUnknown() {
	xxx_messageInfo_Clear.DiscardUnknown(m)
}

var xxx_messageInfo_Clear proto.InternalMessageInfo

func (m *Clear) GetLic() *License {
	if m != nil {
		return m.Lic
	}
	return nil
}

func (m *Clear) GetCipher() *Cipher {
	if m != nil {
		return m.Cipher
	}
	return nil
}

func (m *Clear) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type Cipher struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cipher) Reset()         { *m = Cipher{} }
func (m *Cipher) String() string { return proto.CompactTextString(m) }
func (*Cipher) ProtoMessage()    {}
func (*Cipher) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49f361b44d91b57, []int{18}
}

func (m *Cipher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cipher.Unmarshal(m, b)
}
func (m *Cipher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cipher.Marshal(b, m, deterministic)
}
func (m *Cipher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cipher.Merge(m, src)
}
func (m *Cipher) XXX_Size() int {
	return xxx_messageInfo_Cipher.Size(m)
}
func (m *Cipher) XXX_DiscardUnknown() {
	xxx_messageInfo_Cipher.DiscardUnknown(m)
}

var xxx_messageInfo_Cipher proto.InternalMessageInfo

func (m *Cipher) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Host)(nil), "proto.Host")
	proto.RegisterType((*Product)(nil), "proto.Product")
	proto.RegisterType((*Board)(nil), "proto.Board")
	proto.RegisterType((*Bios)(nil), "proto.Bios")
	proto.RegisterType((*Cpu)(nil), "proto.Cpu")
	proto.RegisterType((*Mem)(nil), "proto.Mem")
	proto.RegisterType((*Network)(nil), "proto.Network")
	proto.RegisterType((*Hardware)(nil), "proto.Hardware")
	proto.RegisterType((*Attrs)(nil), "proto.Attrs")
	proto.RegisterType((*Node)(nil), "proto.Node")
	proto.RegisterType((*SerialNum)(nil), "proto.SerialNum")
	proto.RegisterMapType((map[string]*Node)(nil), "proto.SerialNum.NodesEntry")
	proto.RegisterType((*App)(nil), "proto.App")
	proto.RegisterType((*Attr)(nil), "proto.Attr")
	proto.RegisterType((*License)(nil), "proto.License")
	proto.RegisterMapType((map[string]*App)(nil), "proto.License.AppsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.License.DevicesEntry")
	proto.RegisterType((*AuthReq)(nil), "proto.AuthReq")
	proto.RegisterMapType((map[string]*App)(nil), "proto.AuthReq.AppsEntry")
	proto.RegisterType((*AuthResp)(nil), "proto.AuthResp")
	proto.RegisterType((*UntiedReq)(nil), "proto.UntiedReq")
	proto.RegisterType((*Clear)(nil), "proto.Clear")
	proto.RegisterType((*Cipher)(nil), "proto.Cipher")
}

func init() { proto.RegisterFile("edda.core.proto", fileDescriptor_c49f361b44d91b57) }

var fileDescriptor_c49f361b44d91b57 = []byte{
	// 987 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5b, 0x6b, 0x1b, 0x47,
	0x14, 0x46, 0x5a, 0x5d, 0xac, 0xa3, 0xf8, 0xc2, 0x60, 0x82, 0x50, 0x4d, 0xea, 0x2e, 0xb4, 0xa4,
	0x97, 0xb8, 0x54, 0x25, 0x50, 0xf2, 0x26, 0xab, 0x81, 0x40, 0x63, 0x53, 0x26, 0x94, 0x3c, 0x8f,
	0x77, 0x4e, 0xbb, 0x8b, 0xb5, 0x3b, 0xd3, 0x99, 0x95, 0x1c, 0xf5, 0xb1, 0x7f, 0x25, 0xd0, 0x97,
	0xfe, 0x87, 0xfe, 0x9b, 0xfe, 0x8f, 0x72, 0xe6, 0xb2, 0x5a, 0x39, 0x4a, 0xc9, 0x43, 0x9e, 0x34,
	0xe7, 0x32, 0xe7, 0xf2, 0x7d, 0xdf, 0x8e, 0xe0, 0x18, 0xa5, 0x14, 0x17, 0x99, 0x32, 0x78, 0xa1,
	0x8d, 0xaa, 0x15, 0xeb, 0xbb, 0x9f, 0x34, 0x87, 0xde, 0x0b, 0x65, 0x6b, 0x76, 0x06, 0xa3, 0x52,
	0x64, 0x79, 0x51, 0x61, 0x21, 0x27, 0x9d, 0xf3, 0xce, 0xe3, 0x11, 0xdf, 0x3a, 0xd8, 0x23, 0x80,
	0x7c, 0xa3, 0xd1, 0xac, 0x0b, 0xab, 0xcc, 0xa4, 0xeb, 0xc2, 0x2d, 0x0f, 0x4b, 0xe1, 0x81, 0x30,
	0x59, 0x5e, 0xd4, 0x98, 0xd5, 0x2b, 0x83, 0x93, 0xc4, 0x65, 0xec, 0xf8, 0xd2, 0x2b, 0x18, 0xfe,
	0x6c, 0x94, 0x5c, 0x65, 0x35, 0x63, 0xd0, 0xab, 0x44, 0x89, 0xa1, 0x8f, 0x3b, 0xb3, 0x87, 0x30,
	0x58, 0x63, 0x25, 0x9b, 0xf2, 0xc1, 0x22, 0xbf, 0x45, 0x53, 0x88, 0x65, 0x28, 0x1a, 0xac, 0xf4,
	0x27, 0xe8, 0x5f, 0x2a, 0x61, 0xe4, 0x47, 0x29, 0xf6, 0x08, 0x7a, 0x97, 0x85, 0xb2, 0xad, 0x7b,
	0x9d, 0xf6, 0xbd, 0xf4, 0x6d, 0x07, 0x92, 0x85, 0x5e, 0xbd, 0x2f, 0xce, 0x4e, 0xa1, 0x5f, 0x2a,
	0x89, 0xcb, 0xd0, 0xce, 0x1b, 0xe4, 0xb5, 0x1a, 0x51, 0xba, 0x66, 0x87, 0xdc, 0x1b, 0xe4, 0xcd,
	0x44, 0x96, 0xe3, 0xa4, 0xe7, 0xbd, 0xce, 0xa0, 0x2d, 0x32, 0xbd, 0xb2, 0x93, 0xbe, 0x73, 0xba,
	0xb3, 0xcb, 0x54, 0x06, 0xed, 0x64, 0x10, 0x32, 0xc9, 0x60, 0x13, 0x18, 0xd6, 0xb9, 0x41, 0x21,
	0xed, 0x64, 0xe8, 0xfc, 0xd1, 0x4c, 0xbf, 0x85, 0xe4, 0x0a, 0x4b, 0x2a, 0x55, 0x6f, 0x74, 0x03,
	0x08, 0x9d, 0xb7, 0xa3, 0x74, 0x5b, 0xa3, 0xa4, 0xaf, 0x61, 0x78, 0x8d, 0xf5, 0x9d, 0x32, 0xb7,
	0xb4, 0x99, 0x34, 0xc5, 0x1a, 0x9b, 0xcd, 0xbc, 0x45, 0xcc, 0x97, 0x22, 0x13, 0x52, 0x1a, 0xb4,
	0x36, 0x32, 0xbf, 0xf5, 0xec, 0xdf, 0x31, 0xfd, 0xb3, 0x0b, 0x07, 0x2f, 0x84, 0x91, 0x77, 0xc2,
	0x20, 0xfb, 0x14, 0x7a, 0xb9, 0xb2, 0xb5, 0x2b, 0x3c, 0x9e, 0x8d, 0xbd, 0xfe, 0x2e, 0x48, 0x75,
	0xdc, 0x05, 0xd8, 0x63, 0x18, 0x6a, 0xaf, 0x0c, 0xd7, 0x60, 0x3c, 0x3b, 0x0a, 0x39, 0x41, 0x2f,
	0x3c, 0x86, 0x59, 0x0a, 0xfd, 0x1b, 0x22, 0xdd, 0x75, 0x1b, 0xcf, 0x1e, 0x84, 0x3c, 0x27, 0x04,
	0xee, 0x43, 0xd4, 0xee, 0xa6, 0x50, 0xd6, 0xc1, 0xbb, 0x6d, 0x47, 0xf4, 0x72, 0x17, 0x60, 0x67,
	0x90, 0x64, 0x7a, 0xe5, 0x90, 0x1e, 0xcf, 0x20, 0xc4, 0x17, 0x7a, 0xc5, 0xc9, 0x4d, 0xd1, 0x12,
	0x4b, 0x07, 0xf9, 0x36, 0x7a, 0x85, 0x25, 0x27, 0x37, 0xfb, 0x0a, 0x0e, 0x2a, 0x8f, 0x18, 0xa1,
	0x9f, 0xb4, 0x66, 0x0d, 0x40, 0xf2, 0x26, 0x9e, 0x96, 0xd0, 0x9f, 0xd7, 0xb5, 0xb1, 0x7b, 0x15,
	0xca, 0xa0, 0x47, 0x10, 0x06, 0x44, 0xdd, 0xd9, 0x61, 0x59, 0x0b, 0x53, 0xbb, 0xed, 0x12, 0xee,
	0x0d, 0xf2, 0xe6, 0x77, 0xa5, 0x7c, 0xea, 0x16, 0x1a, 0x71, 0x6f, 0xb0, 0x13, 0x48, 0x2a, 0x75,
	0xe7, 0x96, 0x48, 0x38, 0x1d, 0xd3, 0xd7, 0xd0, 0xbb, 0x56, 0x12, 0x09, 0x23, 0x41, 0x6d, 0x03,
	0xde, 0x11, 0x23, 0x37, 0x0a, 0xf7, 0x21, 0xf6, 0x35, 0x1c, 0xe4, 0x81, 0x9e, 0x00, 0xf9, 0x71,
	0xa4, 0x25, 0xb8, 0x79, 0x93, 0x90, 0xfe, 0xdd, 0x81, 0xd1, 0x2b, 0xf7, 0x9d, 0x5c, 0xaf, 0x4a,
	0x6a, 0x6c, 0x9b, 0x27, 0x82, 0x8e, 0xec, 0x3b, 0xe8, 0x57, 0x4a, 0x22, 0xa9, 0x83, 0x00, 0xf9,
	0x24, 0x54, 0x6a, 0xae, 0x5c, 0xd0, 0x58, 0xf6, 0x79, 0x55, 0x9b, 0x0d, 0xf7, 0x99, 0xb4, 0xbd,
	0x14, 0x35, 0x86, 0x45, 0xdd, 0x79, 0xfa, 0x1c, 0x60, 0x9b, 0x48, 0x6d, 0x6e, 0x71, 0x13, 0xdb,
	0xdc, 0xe2, 0x86, 0x7d, 0x06, 0xfd, 0xb5, 0x58, 0xae, 0xe2, 0xc0, 0x91, 0x58, 0xba, 0xc3, 0x7d,
	0xe4, 0x59, 0xf7, 0x87, 0x4e, 0xfa, 0x57, 0x07, 0x92, 0xb9, 0xd6, 0x7b, 0x41, 0x0f, 0x45, 0xbb,
	0x3b, 0x45, 0x3d, 0x58, 0x89, 0x9b, 0x7d, 0xdc, 0x02, 0x2b, 0x62, 0xf5, 0x10, 0x06, 0xf8, 0x46,
	0x17, 0xc6, 0x7f, 0xb0, 0x09, 0x0f, 0x16, 0x9b, 0xc2, 0x41, 0x51, 0xd9, 0x5a, 0x54, 0x19, 0x06,
	0x1a, 0x1a, 0x9b, 0xde, 0xc3, 0x52, 0xbc, 0x79, 0x59, 0xfc, 0x8a, 0x8b, 0x4d, 0xb6, 0x44, 0xa7,
	0xa6, 0x84, 0xef, 0xf8, 0xd2, 0x4b, 0xe8, 0x51, 0x9b, 0x0f, 0x1c, 0xf4, 0x34, 0x6e, 0x1f, 0xb4,
	0xe1, 0x8c, 0xf4, 0xdf, 0x2e, 0x0c, 0x5f, 0x16, 0x19, 0x56, 0xd6, 0xdd, 0x59, 0x6e, 0x89, 0x59,
	0x16, 0x32, 0x52, 0xd5, 0xdd, 0x52, 0xf5, 0x14, 0x86, 0x12, 0xd7, 0x45, 0x86, 0x71, 0xe1, 0x48,
	0x56, 0x28, 0x72, 0xf1, 0xa3, 0x8f, 0x7a, 0xb2, 0x62, 0x2e, 0xad, 0xfa, 0x1b, 0x56, 0x68, 0x88,
	0x32, 0x0f, 0x42, 0x63, 0x13, 0x3c, 0x2b, 0xed, 0xc8, 0xf4, 0x20, 0x04, 0x8b, 0xfe, 0x50, 0x96,
	0xf7, 0xf6, 0xdf, 0x3a, 0xd8, 0x37, 0xd0, 0x13, 0x5a, 0xc7, 0x6f, 0x68, 0x72, 0x6f, 0x8a, 0xb9,
	0xd6, 0x61, 0x04, 0x97, 0x35, 0x7d, 0x06, 0x0f, 0xda, 0x83, 0xed, 0x11, 0xc7, 0x69, 0x5b, 0x1c,
	0xa3, 0x96, 0x1e, 0xa6, 0x0b, 0x18, 0x35, 0xe5, 0xf6, 0x5c, 0x3c, 0xdf, 0x55, 0x55, 0xfc, 0xe0,
	0xe7, 0x5a, 0xb7, 0x45, 0xf5, 0xb6, 0x03, 0xc3, 0xf9, 0xaa, 0xce, 0x39, 0xfe, 0xce, 0x3e, 0x87,
	0x41, 0x56, 0xe8, 0x3c, 0xbc, 0x94, 0xe3, 0xd9, 0x61, 0x7c, 0x41, 0x9c, 0x93, 0x87, 0x60, 0xb3,
	0x61, 0xb2, 0xb3, 0x61, 0x28, 0xf2, 0xce, 0x86, 0x1f, 0x65, 0xca, 0x57, 0x70, 0xe0, 0xeb, 0x5b,
	0xfd, 0xa1, 0x53, 0x9e, 0x93, 0x68, 0xb2, 0x7b, 0xcf, 0x6e, 0xa0, 0x81, 0x44, 0x94, 0xa5, 0x4f,
	0x60, 0xf4, 0x4b, 0x55, 0x17, 0x28, 0x69, 0xf7, 0x13, 0x48, 0x84, 0xd6, 0x71, 0x32, 0xa1, 0x35,
	0x3b, 0x82, 0x6e, 0x23, 0xb1, 0x6e, 0x21, 0x53, 0x09, 0xfd, 0xc5, 0x12, 0x45, 0x53, 0xb9, 0xf3,
	0xde, 0xca, 0xad, 0x11, 0xbb, 0xff, 0x37, 0xe2, 0x9e, 0xb7, 0x22, 0x3d, 0x83, 0xc1, 0xa2, 0x89,
	0x66, 0x4a, 0x36, 0x5f, 0x0f, 0x9d, 0x67, 0xff, 0x74, 0xe0, 0x90, 0x80, 0x50, 0xa6, 0xf8, 0x43,
	0xd4, 0x85, 0xaa, 0xe8, 0xbd, 0xe3, 0x68, 0xd5, 0x72, 0x8d, 0x92, 0xed, 0xb6, 0x99, 0x9e, 0xdc,
	0x7f, 0xae, 0xd8, 0x13, 0x80, 0x78, 0x1b, 0x25, 0x3b, 0xda, 0x65, 0x6e, 0x7a, 0xbc, 0x63, 0x5b,
	0xcd, 0xbe, 0x84, 0x81, 0x07, 0x88, 0xc5, 0x52, 0x0d, 0x5e, 0xd3, 0xdd, 0x5e, 0xec, 0x0b, 0x18,
	0x3a, 0x70, 0xde, 0x9d, 0x22, 0xbe, 0xd2, 0x2e, 0x7c, 0x33, 0x70, 0xc6, 0xf7, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x07, 0x48, 0x6b, 0xb5, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorizationClient is the client API for Authorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizationClient interface {
	Resolved(ctx context.Context, in *Cipher, opts ...grpc.CallOption) (*SerialNum, error)
	Authorized(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	Untied(ctx context.Context, in *UntiedReq, opts ...grpc.CallOption) (*Cipher, error)
	Cleared(ctx context.Context, in *Cipher, opts ...grpc.CallOption) (*Clear, error)
}

type authorizationClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationClient(cc *grpc.ClientConn) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) Resolved(ctx context.Context, in *Cipher, opts ...grpc.CallOption) (*SerialNum, error) {
	out := new(SerialNum)
	err := c.cc.Invoke(ctx, "/proto.Authorization/Resolved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) Authorized(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/proto.Authorization/Authorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) Untied(ctx context.Context, in *UntiedReq, opts ...grpc.CallOption) (*Cipher, error) {
	out := new(Cipher)
	err := c.cc.Invoke(ctx, "/proto.Authorization/Untied", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) Cleared(ctx context.Context, in *Cipher, opts ...grpc.CallOption) (*Clear, error) {
	out := new(Clear)
	err := c.cc.Invoke(ctx, "/proto.Authorization/Cleared", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServer is the server API for Authorization service.
type AuthorizationServer interface {
	Resolved(context.Context, *Cipher) (*SerialNum, error)
	Authorized(context.Context, *AuthReq) (*AuthResp, error)
	Untied(context.Context, *UntiedReq) (*Cipher, error)
	Cleared(context.Context, *Cipher) (*Clear, error)
}

func RegisterAuthorizationServer(s *grpc.Server, srv AuthorizationServer) {
	s.RegisterService(&_Authorization_serviceDesc, srv)
}

func _Authorization_Resolved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cipher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).Resolved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorization/Resolved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).Resolved(ctx, req.(*Cipher))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_Authorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).Authorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorization/Authorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).Authorized(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_Untied_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntiedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).Untied(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorization/Untied",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).Untied(ctx, req.(*UntiedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_Cleared_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cipher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).Cleared(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorization/Cleared",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).Cleared(ctx, req.(*Cipher))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolved",
			Handler:    _Authorization_Resolved_Handler,
		},
		{
			MethodName: "Authorized",
			Handler:    _Authorization_Authorized_Handler,
		},
		{
			MethodName: "Untied",
			Handler:    _Authorization_Untied_Handler,
		},
		{
			MethodName: "Cleared",
			Handler:    _Authorization_Cleared_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edda.core.proto",
}
